### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.eth_hash.utils'

### ISSUE THREAD

**Issue by Tony186x** [witee-star/BTCRecover-Advance#3]
anybody know what's going on here? I installed pip install eth-hash and pip install eth-utils, but is still not working, heres the full message: 

          Traceback (most recent call last):
            File "/home/kali/Desktop/Crypto/BTCRecover-Advance/btcrecover.py", line 30, in <module>
              from btcrecover import btcrpass
            File "/home/kali/Desktop/Crypto/BTCRecover-Advance/btcrecover/__init__.py", line 2, in <module>
              from .btcrpass import *
            File "/home/kali/Desktop/Crypto/BTCRecover-Advance/btcrecover/btcrpass.py", line 36, in <module>
              from lib.eth_hash.auto import keccak
            File "/home/kali/Desktop/Crypto/BTCRecover-Advance/lib/eth_hash/auto.py", line 1, in <module>
              from lib.eth_hash.backends.auto import (
            File "/home/kali/Desktop/Crypto/BTCRecover-Advance/lib/eth_hash/backends/auto.py", line 1, in <module>
              from lib.eth_hash.utils import (
          ModuleNotFoundError: No module named 'lib.eth_hash.utils'

Thank you

**Comment by TCRetriever** [comment]
Have you installed -r requirements.txt use python3

**Comment by TCRetriever** [comment]
Can you please share me the command you were using?

**Comment by got2bi** [comment]
Got same error even after installed requirements and requirements full

**Comment by TCRetriever** [comment]
https://github.com/witee-star/BTCRecover-master I fixed all issues please go to new enhanced repo :)
