### ISSUE TITLE
Error BTCRecover-Advance

### ISSUE THREAD

**Issue by bit74coin-beep** [witee-star/BTCRecover-Advance#7]
Good day,
I'm trying to save main wallet with BTCRecover-Advance. but I get errors, I'm not a programmer because of that, I wanted to ask how you can fix the error.
 Kind regards
Stanislaw

C:\Users\HOME MAINKAI\Desktop\BTCRecover-Advance>py btcrecover.py --wallet wallet.dat --passwordlist rockyou.txt --enable-gpu
Traceback (most recent call last):
  File "C:\Users\HOME MAINKAI\Desktop\BTCRecover-Advance\btcrecover.py", line 30, in <module>
    from btcrecover import btcrpass
  File "C:\Users\HOME MAINKAI\Desktop\BTCRecover-Advance\btcrecover\__init__.py", line 2, in <module>
    from .btcrpass import *
  File "C:\Users\HOME MAINKAI\Desktop\BTCRecover-Advance\btcrecover\btcrpass.py", line 36, in <module>
    from lib.eth_hash.auto import keccak
  File "C:\Users\HOME MAINKAI\Desktop\BTCRecover-Advance\lib\eth_hash\auto.py", line 1, in <module>
    from lib.eth_hash.backends.auto import (
  File "C:\Users\HOME MAINKAI\Desktop\BTCRecover-Advance\lib\eth_hash\backends\auto.py", line 1, in <module>
    from lib.eth_hash.utils import (
ModuleNotFoundError: No module named 'lib.eth_hash.utils'

**Comment by ne-tort** [comment]
I have the same problem. Please tell me how to solve it

**Comment by TCRetriever** [comment]
Contact me on telegram. It's a python issue - sameerresiex
